apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
 - target:
     kind: Deployment
     name: rabbitmq-cluster-operator
   patch: |-
     - op: replace
       path: /spec/template/spec/containers/0/resources
       value:
         requests: { cpu: "200m", memory: 500Mi }
         limits:   { cpu: "200m", memory: 500Mi }
